[package]
name = "polnareff"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"
incremental = false

[profile.release]
panic = "abort"

[build-dependencies]
cc = "1.0"

[dependencies]


