[build]
rustflags = ["-Clink-args=-Map=target/i586-polnareff-none/debug/polnareff.map"]
target = "i586-polnareff-none.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.'cfg(target_os = "none")']
runner = "qemu-system-i386 -debugcon stdio -kernel"

